# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2527a5819957614f7c4f4084542d3f79c2d2e05236f9664410704368190682ffc75ff30f476ba2e1c22c62f2c06a83bf363c47f996f162ca0e437d7dad4e0689

test:
  secret_key_base: 8b66c06d7c508cd17b2014c07f45725eb98e65bad79deca4999d24c48d6b26d4624bc32f0e64e0a2449473fe5d3e22c6c6aaf2c2df715b0125cdadf5a8cc32ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
